version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src/backend:/app
    ports:
      - "8000:8000" # Expunem doar API Gateway-ul către exterior

  pdf-parser-microservice:
    build:
      context: ./src/pdf-parser-microservice
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./src/pdf-parser-microservice:/app
    # Nu expunem portul, comunicarea se face intern

  bedrock-client-microservice:
    build:
      context: ./src/bedrock-client-microservice
    command: uvicorn src.main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src/bedrock-client-microservice:/app

  knowledge-graph-microservice:
    build:
      context: ./src/knowledge-graph-microservice
    command: uvicorn src.main:app --host 0.0.0.0 --port 8003 --reload
    volumes:
      - ./src/knowledge-graph-microservice:/app

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend/src:/app/src
      - ./src/frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true # Necesar pentru hot-reloading în Docker pe unele sisteme